[package]
name = "pybushka"
version = "0.0.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pybushka"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
pyo3-asyncio = { version =  "0.17", features = ["tokio-runtime"] }
redis = { path = "../redis-rs", features = ["aio", "tokio-comp", "connection-manager"] }
tokio = { version = "^1.23", features = ["rt", "macros", "rt-multi-thread", "time"] }

[package.metadata.maturin]
python-source = "python"
